version: '3.8'

services:
  # Base de Datos para los Metadatos de las fotos
  postgres_db:
    image: postgres:15-alpine
    container_name: local_photo_db
    restart: always
    environment:
      POSTGRES_USER: admin_fotos
      POSTGRES_PASSWORD: SuperPasswordSeguro123
      POSTGRES_DB: photo_cloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Almacenamiento de Objetos para las Fotos Originales
  minio_storage:
    image: minio/minio
    container_name: local_photo_storage
    restart: always
    ports:
      - "9000:9000"       # API para que el backend suba/baje bytes
      - "9001:9001"       # Consola Web para administrar visualmente
    environment:
      MINIO_ROOT_USER: admin_storage
      MINIO_ROOT_PASSWORD: StoragePassword123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: